python main.py \
    --exp_name AnimeInterpDataVectorIntermediate \
    --batch_size 4 \
    --test_batch_size 4 \
    --dataset anime_interp \
    --model cain \
    --max_epoch 200 \
    --lr 0.0001 \
    --data_root /mnt/WDRed/MachineLearning/data/anime/datasets_424_240/train_10k \
    --test_data_root /mnt/WDRed/MachineLearning/data/anime/datasets_424_240/test_2k_540p \
    --svg_dir /mnt/WDRed/MachineLearning/data/anime/datasets_424_240/train_10k_vectorized \
    --test_svg_dir /mnt/WDRed/MachineLearning/data/anime/datasets_424_240/test_2k_540p_vectorized \
    --vector_intermediate